---
title: "Lab 9"
author: "Alice Zheng"
date: "3/25/2020"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
```

### Daily Reports
```{r}
report_03_20_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-20-2020.csv")) %>%
  rename(Country.Region = "Country/Region", Province.State = "Province/State")
```

```{r}
report_03_20_2020 %>% 
  filter (Country.Region == "US") %>% 
  ggplot(aes(x = Confirmed,  y = reorder(Province.State, Confirmed))) + 
    geom_point() +
    ggtitle("Confirmed cases for each US State 3/20/20") +
    ylab("Country/Region") +
    xlab("Confirmed Cases")
```


```{r}
report_03_20_2020 %>% 
  filter (Country.Region == "US") %>% 
  ggplot(aes(x = Deaths,  y = reorder(Province.State, Deaths))) + 
    geom_point() +
    ggtitle("Confirmed deaths for each US State 3/20/20") +
    ylab("Country/Region") +
    xlab("Confirmed Deaths")
```



```{r}
report_03_20_2020 %>% 
  group_by(Country.Region) %>% 
  summarise(Deaths = sum(Deaths)) %>% 
  arrange(desc(Deaths)) %>% 
  slice(1:20) %>% 
  ggplot(aes(y = Deaths, x = reorder(Country.Region, Deaths))) +
  geom_bar(stat = 'identity') +
  ggtitle("The 20 Countries with the most reported COV19-related deaths") +
  ylab("Country/Region") +
  xlab("Deaths") +
  coord_flip()
```


### Time Series
```{r}
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province.State = "Province/State", Country.Region = "Country/Region")
```

```{r}
time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province.State, Country.Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") %>% 
               group_by(Country.Region,Date) %>% 
               summarise(Confirmed = sum(Confirmed))
time_series_confirmed_long$Date <- mdy(time_series_confirmed_long$Date)
```

```{r}
time_series_confirmed_long %>% 
  filter (Country.Region %in% c("China","Iran", "Spain",
                                "Italy", "US", "Germany")) %>% 
    ggplot(aes(x = Date,  y = Confirmed)) + 
    geom_point() +
    geom_line() +
    ggtitle("Countries Most Confirmed COVID-19 Cases") +
    facet_wrap(~Country.Region, ncol=2, scales="free_y")
```

```{r}
time_series_confirmed_long %>% 
  filter (Country.Region %in% c("China","Iran", "Spain",
                                "Italy", "US", "Germany")) %>% 
    ggplot(aes(x = Date,  y = Confirmed, color = Country.Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("Most Confirmed COVID-19 Cases")
```

### Visualizing Data on Maps
```{r}
library(maps)
library(viridis)
```

```{r}
world <- map_data("world")
mybreaks <- c(1, 20, 100, 1000, 50000)
```

###
```{r}
ggplot() +
  geom_polygon(data = world, aes(x=long, y = lat, group = group), fill="pink", alpha=0.3) +
  ggtitle("Map of Confirmed COVID-19 Cases 3/20/20")+
  geom_point(data=time_series_confirmed, aes(x=Long, y=Lat, size=`3/20/20`, color=`3/20/20`),stroke=F, alpha=0.7) +
  scale_size_continuous(name="Cases", trans="log", range=c(1,7),breaks=mybreaks, labels = c("1-19", "20-99", "100-999", "1,000-49,999", "50,000+")) +
  scale_color_viridis_c(option="inferno",name="Cases", trans="log",breaks=mybreaks, labels = c("1-19", "20-99", "100-999", "1,000-49,999", "50,000+")) +
  theme_void() + 
  guides( colour = guide_legend()) +
  labs(caption = "") +
  theme(
    legend.position = "bottom",
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#ffffff", color = NA), 
    panel.background = element_rect(fill = "#ffffff", color = NA), 
    legend.background = element_rect(fill = "#ffffff", color = NA)
  )
```

```{r}
time_series_confirmed_long2 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
    rename(Province.State = "Province/State", Country.Region = "Country/Region") %>%
    pivot_longer(-c(Province.State, Country.Region, Lat, Long),
    names_to = "Date", values_to = "cumulative_cases") %>%
    mutate(Date = mdy(Date) - days(1),
        Place = paste(Lat,Long,sep="_")) %>%
    group_by(Place,Date) %>%
        summarise(cumulative_cases = ifelse(sum(cumulative_cases)>0,
        sum(cumulative_cases),NA_real_),
        Lat = mean(Lat),
        Long = mean(Long)) %>%
    mutate(Pandemic_day = as.numeric(Date - min(Date)))
```


```{r}
static <- ggplot(subset(time_series_confirmed_long2,Date %in% seq(min(Date)+14,max(Date),5)),
            aes(x = Long, y = Lat, size = cumulative_cases/1000)) +
            borders("world", colour = NA, fill = "grey90") +
            theme_bw() +
            geom_point(shape = 21, color='pink', fill='pink', alpha = 0.5) +
            labs(title = 'COVID-19 spread',x = '', y = '',
                 size="Cases (x1000))") +
            theme(legend.position = "right") +
            coord_fixed(ratio=1)+
            facet_wrap(.~Date,nrow=5)
static
```





