---
title: "Lab 2"
author: "Alice Zheng"
output: html_document
---

### Excercise 1
```{r}
v1 <- c(1,3,6,9,12)
v2 <- c(1,0,1,0,1)
v1 + v2
v1 - v2
v1 * v2
v1 / v2
```

### Excercise 2
```{r}
v1 <- c(0,1,2,3)
str(v1)
v2 <- c("aa","bb","cc","dd")
str(v2)
v3 <- c("aa",1,"bb",2)
str(v3)
```

### Excercise 3
```{r} 
genotype1 <- c("AA","AA","AG","GG","GG")
genotype2 <- c("AA","AA","GG","GG","GG")
Genotypes <- cbind(genotype1, genotype2)
Genotypes
table(Genotypes)
```

### Excercise 4
```{r} 
treatment1 <- c(0,1,2,3,4)
treatment2 <- c(0,2,4,6,8)
treatment3 <- c(0,3,6,9,12)
time <- c(0,2,4,6,8)
Treatments <- data.frame(treatment1, treatment2, treatment3, time, row.names = time)
Treatments
plot(Treatments$time, Treatments$treatment3)
```

### Excercise 5
```{r} 
SNP_table <- read.table("23andMe_complete.txt", header = TRUE, sep = "\t")
str(SNP_table)
```
chromosome is a factor with 25 levels, it is different from the truncated SNP file because it does not only contain numerical values.

### Excercise 6
```{r} 
levels(SNP_table$genotype)
```

### Excercise 7
```{r} 
SNP_table_A <- subset(SNP_table, genotype == 'A')
table(SNP_table_A$chromosome)
```


